"""
Isolated Player Asset Generator.

Generates a single full-body NFL player illustration on chroma green background.
Output is a high-resolution isolated asset ready for Photoshop compositing.

Style reference: assets/player_ref_left.jpg  (generated by make_player_ref.py)
Resolution:      4K at 3:4 portrait — Pro | 2K — Flash

Player lookup (three ways, in priority order):
  1. --player "CeeDee Lamb"   — look up by name in team roster
  2. --number 88              — look up by jersey number in team roster
  3. --side left              — use the team's default card_players assignment

Facing convention:
  --side left   → player goes on LEFT side of card  → faces RIGHT toward center
  --side right  → player goes on RIGHT side of card → faces LEFT toward center

Usage:
  # Default card player for DAL left slot (CeeDee Lamb):
  venv/bin/python make_player.py --team DAL --side left

  # Specific player by name:
  venv/bin/python make_player.py --team DAL --player "Dak Prescott" --side right

  # Specific player by jersey number:
  venv/bin/python make_player.py --team DAL --number 88 --side left

  # Custom pose / visor overrides:
  venv/bin/python make_player.py --team DAL --number 41 --side left \\
      --pose pass_rush --ball no --model pro
"""

import argparse
import io
import logging
import os
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types
from PIL import Image as PILImage

from cards.sports_data import get_team
from cards.prompt_engine import build_player_prompt, load_player_ref

load_dotenv()
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

MODELS = {
    "pro":   "gemini-3-pro-image-preview",
    "flash": "gemini-3.1-flash-image-preview",
}
ASPECT = "3:4"
SIZE   = {"pro": "4K", "flash": "2K"}


def _resolve_player(team, args):
    """
    Resolve player data from three sources (priority order):
      1. --player NAME  — search roster by name (case-insensitive)
      2. --number NUM   — search roster by jersey number
      3. --side         — use team's default card_players for that slot
    Returns (name, number, position).
    """
    # 1. Explicit name lookup
    if args.player:
        needle = args.player.lower()
        match = next(
            (p for p in team.roster.values() if p.name.lower() == needle),
            None,
        )
        if match is None:
            # fuzzy: any word matches
            match = next(
                (p for p in team.roster.values() if needle in p.name.lower()),
                None,
            )
        if match is None:
            raise ValueError(
                f"Player '{args.player}' not found in {team.abbreviation} roster.\n"
                f"Available: {', '.join(p.name for p in team.roster.values())}"
            )
        return match.name, match.number, match.position

    # 2. Jersey number lookup
    if args.number:
        match = team.roster.get(str(args.number))
        if match is None:
            raise ValueError(
                f"#{args.number} not found in {team.abbreviation} roster."
            )
        return match.name, match.number, match.position

    # 3. Default card slot
    slot = next((p for p in team.card_players if p.side == args.side), None)
    if slot is None:
        raise ValueError(
            f"No default card_players for {team.abbreviation} side={args.side}. "
            "Use --player NAME or --number NUM."
        )
    return slot.name, slot.number, slot.position


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Isolated player asset generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--team",     required=True,  help="Team abbreviation (e.g. KC, DAL)")
    parser.add_argument("--side",     required=True,  choices=["left", "right"],
                        help="Card facing: left=faces right, right=faces left")
    # Player selection — at least one of these, or falls back to card_players default
    sel = parser.add_argument_group("player selection (pick one, or omit for default)")
    sel.add_argument("--player",   default=None, metavar="NAME",
                     help="Player name from roster (e.g. 'CeeDee Lamb')")
    sel.add_argument("--number",   default=None, metavar="NUM",
                     help="Jersey number from roster (e.g. 88)")
    # Overrides
    parser.add_argument("--position", default=None,
                        help="Override position (qb/rb/wr/te/de/dt/lb/cb/db/s)")
    parser.add_argument("--pose",  default=None,
                        choices=["auto", "throwing", "scrambling", "rushing", "route",
                                 "jump_catch", "catching", "stiff_arm", "hurdle",
                                 "speed_rush", "bull_rush", "pass_rush",
                                 "linebacker", "coverage", "press_coverage",
                                 "kicking", "celebration", "athletic"],
                        help="Action pose (default from team data, then auto by position)")
    parser.add_argument("--ball",  default=None,
                        choices=["auto", "true", "yes", "false", "no", "catching"],
                        help="Ball in hand: true/yes, false/no, catching, auto (default from team data)")
    parser.add_argument("--visor",    default="open",
                        choices=["open", "tinted", "none"],
                        help="Helmet visor style")
    parser.add_argument("--model",    default="flash", choices=["pro", "flash"])
    args = parser.parse_args()

    team = get_team(args.team)
    name, number, position = _resolve_player(team, args)
    if args.position:
        position = args.position

    # Pose and ball priority: CLI override > matching card_players slot > auto
    # Match slot by name first (exact player), then fall back to side slot
    slot = next((p for p in team.card_players if p.name == name), None) or \
           next((p for p in team.card_players if p.side == args.side), None)
    pose = args.pose or (slot.pose if slot else "auto")
    ball = args.ball or (slot.ball if slot else "auto")
    # normalise true/false aliases
    if ball == "true":  ball = "yes"
    if ball == "false": ball = "no"

    ref    = load_player_ref(side=args.side)
    prompt = build_player_prompt(
        team=team,
        name=name,
        number=number,
        position=position,
        side=args.side,
        pose=pose,
        ball=ball,
        visor=args.visor,
    )
    model = MODELS[args.model]
    size  = SIZE[args.model]

    out_dir = Path("output/players")
    out_dir.mkdir(parents=True, exist_ok=True)

    team_slug   = team.abbreviation.lower()
    player_slug = name.split()[-1].lower().replace(".", "").replace(" ", "_")
    slug        = f"{team_slug}_{player_slug}_{args.side}"

    log.info(f"Team     : {team.name}")
    log.info(f"Player   : {name} #{number} ({position.upper()})")
    log.info(f"Side     : {args.side} → faces {'right' if args.side == 'left' else 'left'}")
    log.info(f"Pose     : {pose}  |  Ball: {ball}  |  Visor: {args.visor}")
    log.info(f"Model    : {model}  {ASPECT} {size}")
    log.info(f"Prompt   : {len(prompt)} chars")

    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    response = client.models.generate_content(
        model=model,
        contents=[prompt, ref],
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
            image_config=types.ImageConfig(aspect_ratio=ASPECT, image_size=size),
        ),
    )

    raw_img = None
    for part in response.parts:
        if part.thought:
            continue
        if part.text:
            log.info(f"Model: {part.text[:200]}")
        elif part.inline_data is not None:
            raw_img = PILImage.open(io.BytesIO(part.inline_data.data))
            break

    if raw_img is None:
        raise RuntimeError("No image returned from API")

    # Raw chroma green — key out manually in Photoshop
    raw_path = out_dir / f"{slug}_raw.jpg"
    raw_img.save(raw_path, format="JPEG", quality=97)
    log.info(f"Saved    : {raw_path}  ({raw_img.width}×{raw_img.height})")


if __name__ == "__main__":
    main()
