/** Mirrors `cards/sports_data.py` NFL DAL roster (active roster snapshot). */
export const DAL_ROSTER_ROWS: { name: string; number: string; position: string }[] = [
  ["DeMarvion Overshown", "0", "lb"],
  ["P.J. Locke", "1", "db"],
  ["Cobie Durant", "2", "cb"],
  ["Dak Prescott", "4", "qb"],
  ["Bryan Anger", "5", "p"],
  ["Rashan Gary", "7", "lb"],
  ["KaVontae Turpin", "9", "wr"],
  ["Joe Milton III", "10", "qb"],
  ["Sam Howell", "13", "qb"],
  ["Markquese Bell", "14", "s"],
  ["Derion Kendrick", "15", "cb"],
  ["Ryan Flournoy", "19", "wr"],
  ["Caelen Carson", "21", "cb"],
  ["Jaydon Blue", "23", "rb"],
  ["Trikweze Bridges", "25", "cb"],
  ["DaRon Bland", "26", "cb"],
  ["Malik Hooker", "28", "s"],
  ["Javonte Williams", "33", "rb"],
  ["Shavon Revel Jr.", "34", "cb"],
  ["Marist Liufau", "35", "lb"],
  ["Corey Ballentine", "36", "cb"],
  ["Phil Mafah", "37", "rb"],
  ["Alijah Clark", "38", "db"],
  ["Hunter Luepke", "40", "rb"],
  ["Donovan Ezeiruaku", "41", "de"],
  ["Malik Davis", "43", "rb"],
  ["Trent Sieg", "44", "ls"],
  ["Justin Barron", "45", "lb"],
  ["Shemar James", "50", "lb"],
  ["Tyler Booker", "52", "og"],
  ["James Houston", "53", "de"],
  ["Cooper Beebe", "56", "c"],
  ["Tyler Guyton", "60", "ot"],
  ["Ajani Cornelius", "69", "ot"],
  ["Nate Thomas", "71", "ot"],
  ["Matt Hennessy", "72", "og"],
  ["Tyler Smith", "73", "og"],
  ["Trevor Keegan", "76", "og"],
  ["Terence Steele", "78", "ot"],
  ["Jonathan Mingo", "81", "wr"],
  ["Princeton Fant", "85", "te"],
  ["Luke Schoonmaker", "86", "te"],
  ["Jake Ferguson", "87", "te"],
  ["CeeDee Lamb", "88", "wr"],
  ["Brevyn Spann-Ford", "89", "te"],
  ["Tyrus Wheat", "90", "de"],
  ["Otito Ogbonnia", "91", "dt"],
  ["Quinnen Williams", "92", "dt"],
  ["Jay Toia", "93", "dt"],
  ["Kenny Clark", "95", "dt"],
  ["Jonathan Bullard", "98", "de"],
].map((row) => ({ name: row[0], number: row[1], position: row[2] }));
