import type { TeamData } from "./types";

export const NFL_TEAMS: Record<string, TeamData> = {
  BAL: {
    name: "Baltimore Ravens", city: "Baltimore", abbreviation: "BAL", sport: "nfl",
    primaryHex: "#241773", secondaryHex: "#9E7C0C",
    stadiumName: "M&T Bank Stadium",
    uptownsStadiumPrompt: "M&T Bank Stadium illustrated front-facing — brick and steel exterior with arched windows, dark purple and gold banners on the facade, Ravens shield logos on the building panels, trees and landscaping at the base",
    uptownsSkylinePrompt: "Baltimore skyline: the tall cylindrical Baltimore World Trade Center tower centered (tallest, distinctive rounded top), flanked by shorter rectangular downtown office buildings stepping down at varying heights on both sides, Inner Harbor waterfront at the base",
    uptownsSkyPrompt: "Rich purple and gold dusk sky over Baltimore — deep royal purple at the top fading to warm amber and gold near the horizon from the Inner Harbor glow below. Dramatic volumetric clouds at dramatically varied heights: a tall billowing formation high on the left, the Baltimore World Trade Center's distinctive cylindrical top piercing through lower clouds at center, and a wide lower cloud bank on the right — each at a different height, creating a richly irregular silhouette. Deep purple sky visible in gaps between formations. Cinematic, premium, Ravens colors throughout.",
    jerseyPrompt: "deep purple NFL jersey — 'RAVENS' in white block letters across chest, white block numbers with thick black outline on chest and back, white shoulder stripes, purple sleeves with black and gold trim bands",
    pantsPrompt: "black NFL pants with purple and gold side stripes",
    helmetPrompt: "glossy purple helmet, face fully visible through open visor — Ravens shield logo on both sides (black raven head on purple and gold shield with letter B), black face mask, thin gold center stripe",
    numberStyle: "large white block numerals with thick black outline, collegiate style",
    logoPrompt: "Ravens shield: black raven head facing left, purple and gold shield, bold letter B, gold trim border",
    cardPlayers: [
      { name: "Lamar Jackson",  number: "8",  position: "qb", side: "left",  pose: "throwing", ball: "yes" },
      { name: "Derrick Henry",  number: "22", position: "rb", side: "right", pose: "rushing",  ball: "yes" },
    ],
    roster: {},
  },

  KC: {
    name: "Kansas City Chiefs", city: "Kansas City", abbreviation: "KC", sport: "nfl",
    primaryHex: "#E31837", secondaryHex: "#FFB81C",
    stadiumName: "GEHA Field at Arrowhead Stadium",
    uptownsStadiumPrompt: "Arrowhead Stadium illustrated front-facing — distinctive arrowhead-shaped roofline, red brick exterior, Chiefs arrowhead logos on the facade panels, trees and parking lot surrounding",
    uptownsSkylinePrompt: "Kansas City skyline: the Liberty Memorial obelisk tower (tall, slender stone needle) dominates center as the tallest landmark, flanked by downtown office towers of varying heights — some tall glass buildings, some shorter brick — Missouri River glimpsed at the base",
    uptownsSkyPrompt: "Vivid amber and crimson Chiefs sunset sky — deep red-orange at the horizon fading to rich gold above. Dramatic volumetric clouds at dramatically varied heights: a towering golden cloud pillar rising very high on the left, the Liberty Memorial obelisk needle piercing sharply upward at center-left through a lower cloud bank, a wide mid-height cloud formation at center-right, and a smaller scattered group low on the right — each formation at a distinctly different height. Warm cinematic golden-hour light illuminates the cloud bases from below. Rich, saturated, premium Chiefs red and gold throughout.",
    jerseyPrompt: "red NFL jersey — 'CHIEFS' in white block letters across chest, white block numbers with red outline on chest and back, white shoulder panels, red sleeves with white and gold trim bands",
    pantsPrompt: "white NFL pants with red and gold side stripes",
    helmetPrompt: "red helmet, face fully visible through open visor — Chiefs arrowhead logo on both sides (solid red arrowhead with white outline), white face mask, no center stripe",
    numberStyle: "large white block numerals with red outline",
    logoPrompt: "Chiefs arrowhead: solid red arrowhead pointing right, white outline, bold clean design",
    cardPlayers: [
      { name: "Patrick Mahomes", number: "15", position: "qb", side: "left",  pose: "throwing", ball: "yes" },
      { name: "Travis Kelce",    number: "87", position: "te", side: "right", pose: "rushing",  ball: "yes" },
    ],
    roster: {},
  },

  DAL: {
    name: "Dallas Cowboys", city: "Dallas", abbreviation: "DAL", sport: "nfl",
    primaryHex: "#003594", secondaryHex: "#869397",
    stadiumName: "AT&T Stadium",
    uptownsStadiumPrompt: "AT&T Stadium illustrated front-facing — massive domed silver roof, Cowboys star centered on the facade, glass and steel exterior, Cowboys helmet logos on the building panels",
    uptownsSkylinePrompt: "Dallas skyline: Reunion Tower with its distinctive spherical globe top is the most recognizable landmark (mid-height, iconic shape), flanked by tall glass skyscrapers including the Bank of America Plaza and Renaissance Tower at varying heights, deep indigo sky",
    uptownsSkyPrompt: "Vivid Texas noon sky — deep Cowboys navy-blue at the top fading to bright cerulean and warm gold at the horizon. Large dramatic white cumulus clouds at dramatically varied heights: a massive towering cloud column rising very high on the right with Reunion Tower's globe visible just beside it, a wide mid-height cloud bank at center, and lower scattered clouds on the left with Dallas skyline towers poking through at varying heights. Bright, vivid, cinematic Texas sunshine — warm golden light on every cloud surface. Bold contrast, premium collector card atmosphere.",
    jerseyPrompt: "white home NFL jersey — 'COWBOYS' in navy blue block letters across chest, navy blue numbers with silver metallic outline on chest and back, blue shoulder stripe panels, white sleeves with navy trim",
    pantsPrompt: "silver metallic NFL pants with navy and white side stripes",
    helmetPrompt: "high-gloss silver metallic helmet, face fully visible through open visor — iconic blue five-pointed star centered on both sides, blue face mask, no center stripe",
    numberStyle: "large white block numerals with silver metallic outline",
    logoPrompt: "Cowboys star: large blue five-pointed star, white outline, centered on silver helmet panel",
    cardPlayers: [
      { name: "Dak Prescott", number: "4",  position: "qb", side: "left",  pose: "throwing", ball: "yes" },
      { name: "CeeDee Lamb",  number: "88", position: "wr", side: "right", pose: "route",    ball: "no"  },
    ],
    roster: {
      "0":  { name: "DeMarvion Overshown", number: "0",  position: "lb" },
      "1":  { name: "P.J. Locke",          number: "1",  position: "db" },
      "2":  { name: "Cobie Durant",        number: "2",  position: "cb" },
      "4":  { name: "Dak Prescott",        number: "4",  position: "qb" },
      "5":  { name: "Bryan Anger",         number: "5",  position: "p"  },
      "7":  { name: "Rashan Gary",         number: "7",  position: "lb" },
      "9":  { name: "KaVontae Turpin",     number: "9",  position: "wr" },
      "10": { name: "Joe Milton III",      number: "10", position: "qb" },
      "13": { name: "Sam Howell",          number: "13", position: "qb" },
      "14": { name: "Markquese Bell",      number: "14", position: "s"  },
      "15": { name: "Derion Kendrick",     number: "15", position: "cb" },
      "19": { name: "Ryan Flournoy",       number: "19", position: "wr" },
      "21": { name: "Caelen Carson",       number: "21", position: "cb" },
      "23": { name: "Jaydon Blue",         number: "23", position: "rb" },
      "25": { name: "Trikweze Bridges",    number: "25", position: "cb" },
      "26": { name: "DaRon Bland",         number: "26", position: "cb" },
      "28": { name: "Malik Hooker",        number: "28", position: "s"  },
      "33": { name: "Javonte Williams",    number: "33", position: "rb" },
      "34": { name: "Shavon Revel Jr.",    number: "34", position: "cb" },
      "35": { name: "Marist Liufau",       number: "35", position: "lb" },
      "36": { name: "Corey Ballentine",    number: "36", position: "cb" },
      "37": { name: "Phil Mafah",          number: "37", position: "rb" },
      "38": { name: "Alijah Clark",        number: "38", position: "db" },
      "40": { name: "Hunter Luepke",       number: "40", position: "rb" },
      "41": { name: "Donovan Ezeiruaku",   number: "41", position: "de" },
      "43": { name: "Malik Davis",         number: "43", position: "rb" },
      "44": { name: "Trent Sieg",          number: "44", position: "ls" },
      "45": { name: "Justin Barron",       number: "45", position: "lb" },
      "50": { name: "Shemar James",        number: "50", position: "lb" },
      "52": { name: "Tyler Booker",        number: "52", position: "og" },
      "53": { name: "James Houston",       number: "53", position: "de" },
      "56": { name: "Cooper Beebe",        number: "56", position: "c"  },
      "60": { name: "Tyler Guyton",        number: "60", position: "ot" },
      "69": { name: "Ajani Cornelius",     number: "69", position: "ot" },
      "71": { name: "Nate Thomas",         number: "71", position: "ot" },
      "72": { name: "Matt Hennessy",       number: "72", position: "og" },
      "73": { name: "Tyler Smith",         number: "73", position: "og" },
      "76": { name: "Trevor Keegan",       number: "76", position: "og" },
      "78": { name: "Terence Steele",      number: "78", position: "ot" },
      "81": { name: "Jonathan Mingo",      number: "81", position: "wr" },
      "85": { name: "Princeton Fant",      number: "85", position: "te" },
      "86": { name: "Luke Schoonmaker",    number: "86", position: "te" },
      "87": { name: "Jake Ferguson",       number: "87", position: "te" },
      "88": { name: "CeeDee Lamb",         number: "88", position: "wr" },
      "89": { name: "Brevyn Spann-Ford",   number: "89", position: "te" },
      "90": { name: "Tyrus Wheat",         number: "90", position: "de" },
      "91": { name: "Otito Ogbonnia",      number: "91", position: "dt" },
      "92": { name: "Quinnen Williams",    number: "92", position: "dt" },
      "93": { name: "Jay Toia",            number: "93", position: "dt" },
      "95": { name: "Kenny Clark",         number: "95", position: "dt" },
      "98": { name: "Jonathan Bullard",    number: "98", position: "de" },
    },
  },

  GB: {
    name: "Green Bay Packers", city: "Green Bay", abbreviation: "GB", sport: "nfl",
    primaryHex: "#203731", secondaryHex: "#FFB612",
    stadiumName: "Lambeau Field",
    uptownsStadiumPrompt: "Lambeau Field illustrated front-facing — classic circular open-air bowl stadium, dark green and gold exterior, large Packers G logos on the facade panels, snow on the ground, pine trees surrounding the base. The stadium bowl is open at the front — you can see inside the seating bowl, the packed crowd in green and gold, and the field from this front angle.",
    uptownsSkylinePrompt: "Green Bay winter scene: tall pointed pine trees of dramatically varying heights rise above the stadium — some very tall and narrow, others medium, others short — with snow-covered rooftops of low buildings visible between the trees",
    uptownsSkyPrompt: "Crisp Wisconsin winter sky — deep steel grey-blue at the top with warm amber stadium glow rising from below. Dramatic grey-white cloud formations at dramatically varied heights: a tall billowing cloud tower rising high on the left, a very tall snow-dusted pine tree spiking sharply at center-left piercing through a low cloud, a wide mid-height cloud bank at center with another tall pine visible through it, and more pine tips at varying heights on the right — each pine and cloud at a distinctly different height. Cold winter air, light snowfall visible. Packers gold warmth glowing from the stadium lights below the clouds.",
    jerseyPrompt: "dark forest green NFL jersey — 'PACKERS' in gold block letters across chest, gold block numbers with white outline on chest and back, gold shoulder panels, green sleeves with gold and white trim bands",
    pantsPrompt: "gold NFL pants with green and white side stripes",
    helmetPrompt: "matte gold helmet, face fully visible through open visor — Packers G logo on both sides (dark green oval with large white letter G centered), white face mask, no center stripe",
    numberStyle: "large gold block numerals with white outline",
    logoPrompt: "Packers G: dark green oval, large white letter G centered, clean bold design",
    cardPlayers: [
      { name: "Jordan Love", number: "10", position: "qb", side: "left",  pose: "throwing", ball: "yes" },
      { name: "Jayden Reed", number: "11", position: "wr", side: "right", pose: "route",    ball: "no"  },
    ],
    roster: {},
  },

  CHI: {
    name: "Chicago Bears", city: "Chicago", abbreviation: "CHI", sport: "nfl",
    primaryHex: "#0B162A", secondaryHex: "#C83803",
    stadiumName: "Soldier Field",
    uptownsStadiumPrompt: "Soldier Field illustrated front-facing — iconic neoclassical stone columns flanking both sides of the modern bowl, Bears C logos on the facade panels, Lake Michigan visible behind",
    uptownsSkylinePrompt: "Chicago skyline: Willis Tower (Sears Tower) dominates center-left — tallest building with two slim antenna towers at the top. John Hancock Center with distinctive X-bracing stands to the right at second height. Shorter skyscrapers at many varying heights fill the rest. Lake Michigan shoreline at the base.",
    uptownsSkyPrompt: "Dramatic Chicago dusk sky — deep navy blue at the top fading to vivid burnt orange and amber from the city glow near the horizon. Dramatic clouds at dramatically varied heights: Willis Tower's twin steel antenna tips pierce sharply upward through a low cloud bank at center — the antennas are the absolute highest point, far above everything else. John Hancock's X-braced silhouette clears a wider cloud bank at the right at a distinctly lower height. A tall billowing cloud formation rises high on the left. Navy blue sky visible between formations. Bears navy and orange throughout — cinematic Chicago dusk energy.",
    jerseyPrompt: "navy blue NFL jersey — 'BEARS' in orange block letters across chest, orange block numbers with white outline on chest and back, navy shoulder panels, navy sleeves with orange and white trim bands",
    pantsPrompt: "navy blue NFL pants with orange and white side stripes",
    helmetPrompt: "navy blue helmet, face fully visible through open visor — Bears C logo on both sides (bold orange letter C with navy outline), navy face mask, no center stripe",
    numberStyle: "large orange block numerals with white outline",
    logoPrompt: "Bears C: bold orange letter C, navy outline, classic Chicago Bears design",
    cardPlayers: [
      { name: "Caleb Williams", number: "18", position: "qb", side: "left",  pose: "throwing", ball: "yes" },
      { name: "DJ Moore",       number: "2",  position: "wr", side: "right", pose: "route",    ball: "no"  },
    ],
    roster: {},
  },

  LV: {
    name: "Las Vegas Raiders", city: "Las Vegas", abbreviation: "LV", sport: "nfl",
    primaryHex: "#000000", secondaryHex: "#A5ACAF",
    stadiumName: "Allegiant Stadium",
    uptownsStadiumPrompt: "Allegiant Stadium illustrated front-facing — iconic massive smooth black dome, known as the 'Death Star' of NFL stadiums, seamless dark curved roof covering the entire structure, Raiders shield logo on the exterior facade panels, 'ALLEGIANT STADIUM' lettered in large silver text on the EXTERIOR facade wall below the roof — NOT on glass, NOT inside the stadium, exterior signage only, palm trees at the base",
    uptownsSkylinePrompt: "Las Vegas Strip skyline: the Strat (Stratosphere) needle tower rises highest on the right (tallest, extremely slim with small pod near top), the massive spherical Sphere venue dominates the left, the Eiffel Tower replica at Paris Las Vegas stands center, surrounded by casino resort towers of dramatically varying heights",
    uptownsSkyPrompt: "Las Vegas night sky — deep black-purple above with vivid neon glow rising from the Strip: electric pink, magenta, cyan and gold light blazing up from below. Dramatic cloud formations at dramatically varied heights: a wide charcoal cloud bank very high on the left with the MSG Sphere's colorful LED surface glowing below it, the Eiffel Tower replica rising tall and golden at center through a gap in the clouds, the Stratosphere needle piercing sharply upward at the right — the single tallest element — with a lower cloud around it. Each landmark at a distinctly different height. Deep purple-black sky visible between formations, lit by neon from below. Vivid, electric, unmistakably Vegas — Raiders black and silver with neon Strip energy.",
    jerseyPrompt: "black NFL jersey — 'RAIDERS' in silver block letters across chest, silver block numbers with white outline on chest and back, black shoulder panels with silver trim, black sleeves with silver trim bands",
    pantsPrompt: "silver NFL pants with black side stripes",
    helmetPrompt: "high-gloss silver metallic helmet, face fully visible through open visor — Raiders shield logo on both sides (black shield with silver crossed swords and pirate eye patch), black face mask, no center stripe",
    numberStyle: "large silver block numerals with white outline",
    logoPrompt: "Raiders shield: black shield, silver crossed swords, silver football, silver pirate eye patch, bold iconic design",
    cardPlayers: [
      { name: "Maxx Crosby",  number: "98", position: "de", side: "left",  pose: "speed_rush", ball: "no" },
      { name: "Brock Bowers", number: "89", position: "te", side: "right", pose: "rushing",    ball: "yes" },
    ],
    roster: {},
  },
};

export function getTeam(abbr: string): TeamData {
  const team = NFL_TEAMS[abbr.toUpperCase()];
  if (!team) throw new Error(`Team not found: ${abbr}`);
  return team;
}
